[package]
name = "rivets-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
rivets-shared = { path = "../rivets-shared" }
anyhow = "1.0"
lazy-regex = "3.1"
darling = "0.20"

[lib]
proc-macro = true
